# Generated by Django 3.1.7 on 2021-07-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='media/uploads/message_photos/07.07.2021_11.48.04_REC_vRlhH4w.png', upload_to='uploads/profile_pictures'),
        ),
    ]
