# Generated by Django 3.1.7 on 2021-07-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210728_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default-profile.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
